version: '3.3'
services:
  app:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    ports:
    - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=yousef@yousef.com
      - PGADMIN_DEFAULT_PASSWORD=saman400
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=saman400
      - POSTGRES_DB=test
    ports:
      - 5432:5432

